routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('classrooms', 'ClassroomsController');
    Route::resource('courses', 'CoursesController');
    Route::resource('departments', 'DepartmentsController');
    Route::resource('sections', 'SectionsController');
    Route::resource('students', 'StudentsController');
    Route::resource('teachers', 'TeachersController');
    Route::resource('times', 'TimesController');
    Route::resource('users', 'UsersController');
});

Route::middleware(['auth'])->group(function () {
    Route::get('exportTeachers', 'TeachersController@export')->name('teachers.export');
    Route::post('importTeachers', 'TeachersController@import')->name('teachers.import');
    Route::get('exportStudents', 'StudentsController@export')->name('students.export');
    Route::post('importStudents', 'StudentsController@import')->name('students.import');
    Route::get('exportClassrooms', 'ClassroomsController@export')->name('classrooms.export');
    Route::post('importClassrooms', 'ClassroomsController@import')->name('classrooms.import');
});

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $fillable = [
        'Name',
        'Surname',
        'Email',
        'PhoneNumber',
        'DateOfBirth',
        'Pesel',
        'TeacherID',
        'Degree',       
    ];

     /* //wiele kursow, wiele czasu
     public function courses()
     {
         return $this->belongsToMany(Course::class);
     }
 
     public function times()
     {
         return $this->belongsToMany(Time::class);
     }

     public function departments()
     {
         return $this->belongsTo(Department::class);
     } */
}

app/Http/Controllers/TeachersController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Teacher;
use App\Exports\TeachersExport;
use App\Imports\TeachersImport;
use App\Http\Requests\CreateTeacherRequest;
use App\Http\Requests\UpdateTeacherRequest;
use Maatwebsite\Excel\Facades\Excel;

class TeachersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('teachers.index')->with('teachers', Teacher::paginate(4));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('teachers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTeacherRequest $request)
    {
        $teacher = Teacher::create([
            'Name' => $request->Name,
            'Surname' => $request->Surname,
            'Email' => $request->Email,
            'PhoneNumber' => $request->PhoneNumber,
            'DateOfBirth' => $request->DateOfBirth,
            'Pesel' => $request->Pesel,
            'TeacherID' => $request->TeacherID,
            'Degree' => $request->Degree
       ]);
       // flash message
       session()->flash('success', 'Teacher added successfully.');
       // redirect user

       return redirect(route('teachers.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Teacher $teacher)
    {
        return view('teachers.create')->with('teacher', $teacher);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTeacherRequest $request, Teacher $teacher)
    {
        $teacher->update([
            'Name' => $request->Name,
            'Surname' => $request->Surname,
            'Email' => $request->Email,
            'PhoneNumber' => $request->PhoneNumber,
            'DateOfBirth' => $request->DateOfBirth,
            'Pesel' => $request->Pesel,
            'TeacherID' => $request->TeacherID,
            'Degree' => $request->Degree
       ]);
       // flash message
       session()->flash('success', 'Teacher updated successfully.');
       // redirect user

       return redirect(route('teachers.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $teacher = Teacher::where('id', $id)->firstOrFail();
        $teacher->delete();
        session()->flash('success', 'Teacher deleted successfully.');

        return redirect(route('teachers.index'));
    }

    /**
     * Export students to csv file
     *
     */

    public function export()
     {
        return Excel::download(new TeachersExport, 'teachers.csv');
     } 

     /**
     * Import csv file with students
     *
     */

     public function import() 
     {
         Excel::import(new TeachersImport,request()->file('file'));
            
         return back();
     }
}

resources/views/teachers/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card card-default">
  <div class="card-header">
    {{ isset($teacher) ? 'Edit Teacher': 'Add Teacher' }}
  </div>

  <div class="card-body">
    @include('partials.errors')
    <form action="{{ isset($teacher) ? route('teachers.update', $teacher->id) : route('teachers.store') }}" method="POST">
      @csrf

      @if(isset($teacher))
        @method('PUT')
      @endif

      <div class="form-group">
        <label for="Name">Name</label>
        <input type="text" class="form-control" name="Name" id='Name' value="{{ isset($teacher) ? $teacher->Name: '' }}">
      </div>
      <div class="form-group">
        <label for="Surname">Surname</label>
        <input type="text" class="form-control" name="Surname" id='Surname' value="{{ isset($teacher) ? $teacher->Surname: '' }}">
      </div>
      <div class="form-group"> 
           {{-- Czy email ma jakas controlke? --}}
        <label for="Email">Email</label> 
        <input type="text" class="form-control" name="Email" id='Email' value="{{ isset($teacher) ? $teacher->Email: '' }}">
      </div>
      <div class="form-group">
           {{-- Tylko cyfry i max dlugosc --}}
        <label for="PhoneNumber">PhoneNumber</label>
        <input type="number" class="form-control" name="PhoneNumber" id='PhoneNumber' value="{{ isset($teacher) ? $teacher->PhoneNumber: '' }}">
      </div>
      <div class="form-group">
              {{-- wybieraczka jakas tam  --}}
          <label for="DateOfBirth">DateOfBirth</label>
          <input type="text" class="form-control" name="DateOfBirth" id='DateOfBirth' value="{{ isset($teacher) ? $teacher->DateOfBirth : '' }}">
     </div>
     <div class="form-group">
           {{-- tylko liczby i max dlugosc --}}
        <label for="Pesel">Pesel</label>
        <input type="number" class="form-control" name="Pesel" id='Pesel' value="{{ isset($teacher) ? $teacher->Pesel: '' }}">
      </div> 
      <div class="form-group">
        <label for="TeacherID">TeacherID</label>
        <input type="number" class="form-control" name="TeacherID" id='TeacherID' value="{{ isset($teacher) ? $teacher->TeacherID: '' }}">
      </div>
    <div class="form-group">      
      <div class="form-group">
          <label for="Degree">Degree</label>
          @if (isset($teacher))
          <select name="Degree" id="Degree" class="form-control">        
               <option value="licencjat" @if($teacher->Degree == "licencjat") selected @endif>licencjat</option>
               <option value="inżynier" @if($teacher->Degree == "inżynier") selected @endif>inżynier</option>
               <option value="magister" @if($teacher->Degree == "magister") selected @endif>magister</option>          
               <option value="doktor" @if($teacher->Degree == "doktor") selected @endif>doktor</option>     
               <option value="doktor habilitwany" @if($teacher->Degree == "doktor habilitwany") selected @endif>doktor habilitwany</option>
               <option value="profesor" @if($teacher->Degree == "profesor") selected @endif>profesor</option>        
          </select>
          @else
          <select name="Degree" id="Degree" class="form-control">        
               <option value="">Wybierz</option> 
               <option value="licencjat">licencjat</option>
               <option value="inżynier">inżynier</option>
               <option value="magister">magister</option>          
               <option value="doktor">doktor</option>     
               <option value="doktor habilitwany">doktor habilitwany</option>
               <option value="profesor">profesor</option>        
          </select>
          @endif
     </div>
      <div class="form-group">
        <a href="{{route('teachers.index')}}" class="btn btn-secondary">Back</a>
        <button type="submit"  class="btn btn-secondary btn-lg">
          {{ isset($teacher) ? 'Update Teacher': 'Add Teacher' }}
        </button>        
      </div>
    </form>
  </div>
</div>
@endsection

@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script>
     flatpickr('#DateOfBirth', {
       enableTime: false,
       enableSeconds: false
     })
</script>
@endsection

@section('css')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
@endsection

resources/views/teachers/index.blade.php
@extends('layouts.app')

@section('content')

  <div class="d-flex justify-content-end mb-2">
  <a href="{{ route('teachers.create') }}" class="btn btn-secondary btn-lg">Add Teacher</a>
  </div>

  <div class="d-flex justify-content-end mb-5">
  <a href="{{ route('teachers.export') }}" class="btn btn-secondary btn-lg">Export to csv</a>
  </div>
  <div class="d-flex justify-content-end mb-2">
  <form action="{{ route('teachers.import') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <input type="file" name="file" class="form-control d-flex justify-content-end">
    <button class="btn btn-secondary btn-lg">Import Teachers</button>
  </div>

</div>


  <div class="card card-default">
    <div class="card-header">Teachers List</div>
  

  <div class="card-body">
     @include('partials.errors')
    @if($teachers->count() > 0)
      <table class="table text-white">
        <thead>
          <th>Name</th>
          <th>Surname</th>
          <th>Email</th>
          <th>PhoneNumber</th>
          <th>DateOfBirth</th>
          <th>Pesel</th>
          <th>TeacherID</th>
          <th>Degree</th>
          <th></th>
          <th></th>
        </thead>
        <tbody>
          @foreach($teachers as $teacher)
            <tr>
              <td>
                    {{-- name --}}
                    {{ $teacher->Name }}
              </td>
              <td>
                {{-- Surname --}}
                {{ $teacher->Surname }}
              </td>
               <td>
                {{-- Email --}}
                {{ $teacher->Email }}
              </td>
              <td>
               {{-- PhoneNumber --}}
               {{ $teacher->PhoneNumber }}
             </td>
             <td>
               {{-- DateOfBNirth --}}
               {{ $teacher->DateOfBirth }}
             </td>
             <td>
               {{-- Pesel --}}
               {{ $teacher->Pesel }}
             </td>
             <td>
              {{-- Pesel --}}
              {{ $teacher->TeacherID }}
            </td>
             <td>
               {{-- DegreeType --}}
                {{$teacher->Degree}}
             </td>
             <td>
               <a href="{{ route('teachers.edit', $teacher->id) }}" class="btn btn-secondary btn-sm">Edit</a>
             </td>
              <td>
              <form action="{{ route('teachers.destroy', $teacher->id) }}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-secondary btn-sm">
                    Delete
                </button>
              </form>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
      {{$teachers->links()}}
    @else
      <h3 class="text-center">No Teachers Yet</h3>
    @endif
  
</div>

@endsection
@section('scripts')

@endsection

@section('css')

@endsection