routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('classrooms', 'ClassroomsController');
    Route::resource('courses', 'CoursesController');
    Route::resource('departments', 'DepartmentsController');
    Route::resource('sections', 'SectionsController');
    Route::resource('students', 'StudentsController');
    Route::resource('teachers', 'TeachersController');
    Route::resource('times', 'TimesController');
    Route::resource('users', 'UsersController');
});

Route::middleware(['auth'])->group(function () {
    Route::get('exportTeachers', 'TeachersController@export')->name('teachers.export');
    Route::post('importTeachers', 'TeachersController@import')->name('teachers.import');
    Route::get('exportStudents', 'StudentsController@export')->name('students.export');
    Route::post('importStudents', 'StudentsController@import')->name('students.import');
    Route::get('exportClassrooms', 'ClassroomsController@export')->name('classrooms.export');
    Route::post('importClassrooms', 'ClassroomsController@import')->name('classrooms.import');
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
        'Name',
        'Surname',
        'Email',
        'PhoneNumber',
        'IndexNumber',
        'DateOfBirth',
        'Pesel',
        'IsActive',
        'DegreeLevel',
        'DegreeType',       
    ];

    //wiele kursow, wiele section
    public function courses()
    {
        return $this->belongsToMany(Course::class);
    }

    public function sections()
    {
        return $this->belongsToMany(Section::class);
    }

}

app/Http/Controllers/StudentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CreateStudentRequest;
use App\Http\Requests\UpdateStudentRequest;
use App\Student;
use App\Exports\StudentsExport;
use App\Imports\StudentsImport;
use Maatwebsite\Excel\Facades\Excel;

class StudentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('students.index')->with('students', Student::paginate(4));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('students.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateStudentRequest $request)
    {
           $student = Student::create([
                'Name' => $request->Name,
                'Surname' => $request->Surname,
                'Email' => $request->Email,
                'PhoneNumber' => $request->PhoneNumber,
                'DateOfBirth' => $request->DateOfBirth,
                'Pesel' => $request->Pesel,
                'IndexNumber' => $request->IndexNumber,
                'IsActive' => $request->IsActive,
                'DegreeLevel' => $request->DegreeLevel,
                'DegreeType' => $request->DegreeType
           ]);
           // flash message
           session()->flash('success', 'Student added successfully.');
           // redirect user
   
           return redirect(route('students.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        return view('students.create')->with('student', $student);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateStudentRequest $request, Student $student)
    {
        $student->update([
            'Name' => $request->Name,
            'Surname' => $request->Surname,
            'Email' => $request->Email,
            'PhoneNumber' => $request->PhoneNumber,
            'DateOfBirth' => $request->DateOfBirth,
            'Pesel' => $request->Pesel,
            'IndexNumber' => $request->IndexNumber,
            'IsActive' => $request->IsActive,
            'DegreeLevel' => $request->DegreeLevel,
            'DegreeType' => $request->DegreeType
        ]);
          // flash message
          session()->flash('success', 'Student updated successfully.');
          // redirect user
  
          return redirect(route('students.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $student = Student::where('id', $id)->firstOrFail();
        $student->delete();
        session()->flash('success', 'Student deleted successfully.');

        return redirect(route('students.index'));
    }
    /**
     * Export students to csv file
     *
     */

     public function export()
     {
        return Excel::download(new StudentsExport, 'students.csv');
     }  
     
     /**
     * Import csv file with students
     *
     */
     public function import() 
     {
         Excel::import(new StudentsImport,request()->file('file'));
            
         return back();
     }
}

resources/views/students/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card card-default">
  <div class="card-header">
    {{ isset($student) ? 'Edit Student': 'Add Student' }}
  </div>

  <div class="card-body">
    @include('partials.errors')
    <form action="{{ isset($student) ? route('students.update', $student->id) : route('students.store') }}" method="POST">
      @csrf

      @if(isset($student))
        @method('PUT')
      @endif

      <div class="form-group">
        <label for="Name">Name</label>
        <input type="text" class="form-control" name="Name" id='Name' value="{{ isset($student) ? $student->Name: '' }}">
      </div>
      <div class="form-group">
        <label for="Surname">Surname</label>
        <input type="text" class="form-control" name="Surname" id='Surname' value="{{ isset($student) ? $student->Surname: '' }}">
      </div>
      <div class="form-group">
          <label for="IndexNumber">IndexNumber</label>
          <input type="number" class="form-control" name="IndexNumber" id='IndexNumber' value="{{ isset($student) ? $student->IndexNumber: '' }}">
        </div>
      <div class="form-group"> 
           {{-- Czy email ma jakas controlke? --}}
        <label for="Email">Email</label> 
        <input type="text" class="form-control" name="Email" id='Email' value="{{ isset($student) ? $student->Email: '' }}">
      </div>
      <div class="form-group">
           {{-- Tylko cyfry i max dlugosc --}}
        <label for="PhoneNumber">PhoneNumber</label>
        <input type="number" class="form-control" name="PhoneNumber" id='PhoneNumber' value="{{ isset($student) ? $student->PhoneNumber: '' }}">
      </div>
      <div class="form-group">
              {{-- wybieraczka jakas tam  --}}
          <label for="DateOfBirth">DateOfBirth</label>
          <input type="text" class="form-control" name="DateOfBirth" id='DateOfBirth' value="{{ isset($student) ? $student->DateOfBirth : '' }}">
     </div>
     <div class="form-group">
           {{-- tylko liczby i max dlugosc --}}
        <label for="Pesel">Pesel</label>
        <input type="number" class="form-control" name="Pesel" id='Pesel' value="{{ isset($student) ? $student->Pesel: '' }}">
      </div>      
      <div class="form-group">
        <label for="IsActive">IsActive</label>
        @if(isset($student))
          <select name="IsActive" id="IsActive" class="form-control">                      
               <option value="0" @if($student->DegreeLevel == 0) selected @endif>Nie aktywny</option>
               <option value="1" @if($student->DegreeLevel == 1) selected @endif>Aktywny</option>          
          </select>
        @else
          <select name="IsActive" id="IsActive" class="form-control">        
               <option value="">Wybierz</option>
               <option value="0">Nie aktywny</option>
               <option value="1">Aktywny</option>          
          </select>
        @endif
      </div>
      <div class="form-group">
          <label for="DegreeLevel">DegreeLevel</label>
          @if (isset($student))
          <select name="DegreeLevel" id="DegreeLevel" class="form-control">        
               <option value="1" @if($student->DegreeLevel == 1) selected @endif>Pierwszy stopień</option>
               <option value="2" @if($student->DegreeLevel == 2) selected @endif>Drugi stopień</option>          
               <option value="3" @if($student->DegreeLevel == 3) selected @endif>Trzeci stopień</option>          
          </select>
          @else
          <select name="DegreeLevel" id="DegreeLevel" class="form-control">        
               <option value="0">Wybierz</option>
               <option value="1">Pierwszy stopień</option>
               <option value="2">Drugi stopień</option>          
               <option value="3">Trzeci stopień</option>          
          </select>
          @endif
     </div>
      <div class="form-group">
        <label for="DegreeType">DegreeType</label>
          <select name="DegreeType" id="DegreeType" class="form-control"> 
          @if (isset($student))
               <option value="inżynierskie" @if($student->DegreeType == "inżynierskie") selected @endif >inżynierskie</option>
               <option value="licencjackie" @if($student->DegreeType == "licencjackie") selected @endif>licencjackie</option>          
               <option value="magisterskie" @if($student->DegreeType == "magisterskie") selected @endif>magisterskie</option>          
               <option value="doktoranckie" @if($student->DegreeType == "doktoranckie") selected @endif>doktoranckie</option>  
          @else
               <option value="" >Wybierz</option>
               <option value="inżynierskie">inżynierskie</option>
               <option value="licencjackie">licencjackie</option>          
               <option value="magisterskie">magisterskie</option>          
               <option value="doktoranckie">doktoranckie</option>  
          @endif               
          </select>
      </div>
      <div class="form-group">
        <a href="{{route('students.index')}}" class="btn btn-secondary">Back</a>
        <button type="submit"  class="btn btn-secondary btn-lg">
          {{ isset($student) ? 'Update Student': 'Add Student' }}
        </button>        
      </div>
    </form>
  </div>
</div>
@endsection

@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script>
     flatpickr('#DateOfBirth', {
       enableTime: false,
       enableSeconds: false
     })
</script>
@endsection

@section('css')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
@endsection

resources/views/students/index.blade.php
@extends('layouts.app')

@section('content')

  <div class="d-flex justify-content-end mb-2">
  <a href="{{ route('students.create') }}" class="btn btn-secondary btn-lg">Add Student</a>
  </div>

  <div class="d-flex justify-content-end mb-5">
  <a href="{{ route('students.export') }}" class="btn btn-secondary btn-lg">Export to csv</a>
  </div>
  <div class="d-flex justify-content-end mb-2">
  <form action="{{ route('students.import') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <input type="file" name="file" class="form-control d-flex justify-content-end">
    <button class="btn btn-secondary btn-lg">Import Students</button>
  </div>

</div>


  <div class="card card-default">
    <div class="card-header">Students List</div>

  <div class="card-body">
     @include('partials.errors')
    @if($students->count() > 0)
      <table class="table text-white">
        <thead>
          <th>Name</th>
          <th>Surname</th>
          <th>Index</th>
          <th>Email</th>
          <th>PhoneNumber</th>
          <th>DateOfBirth</th>
          <th>Pesel</th>
          <th>IsActive</th>
          <th>DegreeLevel</th>
          <th>DegreeType</th>
          <th></th>
          <th></th>
        </thead>
        <tbody>
          @foreach($students as $student)
            <tr>
              <td>
                    {{-- name --}}
                    {{ $student->Name }}
              </td>
              <td>
                {{-- Surname --}}
                {{ $student->Surname }}
              </td>
              <td>
                {{-- Surname --}}
                {{ $student->IndexNumber }}
              </td>
               <td>
                {{-- Email --}}
                {{ $student->Email }}
              </td>
              <td>
               {{-- PhoneNumber --}}
               {{ $student->PhoneNumber }}
             </td>
             <td>
               {{-- DateOfBNirth --}}
               {{ $student->DateOfBirth }}
             </td>
             <td>
               {{-- Pesel --}}
               {{ $student->Pesel }}
             </td>
             <td>
               {{-- IsActive --}}
              @if($student->IsActive)
                  Aktywny
              @else
                  Nie Aktywny
              @endif
             </td>
             <td>
               @if($student->DegreeLevel == 1)
               Pierwszy stopień
           @else
               Drugi stopień
           @endif
             </td>
             <td>
               {{-- DegreeType --}}
                {{$student->DegreeType}}
             </td>
             <td>
               <a href="{{ route('students.edit', $student->id) }}" class="btn btn-secondary btn-sm">Edit</a>
             </td>
              <td>
              <form action="{{ route('students.destroy', $student->id) }}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-secondary btn-sm">
                    Delete
                </button>
              </form>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
      {{$students->links()}}
    @else
      <h3 class="text-center">No Students Yet</h3>
    @endif
  
</div>
@endsection
@section('scripts')

@endsection

@section('css')

@endsection