routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('classrooms', 'ClassroomsController');
    Route::resource('courses', 'CoursesController');
    Route::resource('departments', 'DepartmentsController');
    Route::resource('sections', 'SectionsController');
    Route::resource('students', 'StudentsController');
    Route::resource('teachers', 'TeachersController');
    Route::resource('times', 'TimesController');
    Route::resource('users', 'UsersController');
});

Route::middleware(['auth'])->group(function () {
    Route::get('exportTeachers', 'TeachersController@export')->name('teachers.export');
    Route::post('importTeachers', 'TeachersController@import')->name('teachers.import');
    Route::get('exportStudents', 'StudentsController@export')->name('students.export');
    Route::post('importStudents', 'StudentsController@import')->name('students.import');
    Route::get('exportClassrooms', 'ClassroomsController@export')->name('classrooms.export');
    Route::post('importClassrooms', 'ClassroomsController@import')->name('classrooms.import');
});

app/Classroom.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Classroom extends Model
{
    protected $fillable = [
        'ClassroomNo',
        'Description',
        'Cpacity',
        'Laboratory',
        'Conversatory',
        'Lecture',
        'Seminar',   
    ];

      //wiele kursow, wiele czasu
     public function courses()
     {
         return $this->belongsToMany(Course::class);
     }
 /*
     public function times()
     {
         return $this->belongsToMany(Time::class);
     }

     public function departments()
     {
         return $this->belongsTo(Department::class);
     } */
}

app/Http/Controllers/ClassroomsController.php
<?php

namespace App\Http\Controllers;

use App\Classroom;
use App\Exports\ClassrooomsExport;
use App\Imports\ClassrooomsImport;
use Illuminate\Http\Request;
use App\Http\Requests\CreateClassroomRequest;
use App\Http\Requests\UpdateClassroomRequest;

use Maatwebsite\Excel\Facades\Excel;

class ClassroomsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('classrooms.index')->with('classrooms', Classroom::paginate(4));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('classrooms.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateClassroomRequest $request)
    {
        $classroom = Classroom::create([
            'ClassroomNo' => $request->ClassroomNo,
            'Desctiption' => $request->Desctiption,
            'Capacity' => $request->Capacity,
            'Laboratory' => $request->Laboratory,
            'Conversatory' => $request->Conversatory,
            'Lecture' => $request->Lecture,
            'Seminar' => $request->Seminar,   
       ]);
       // flash message
       session()->flash('success', 'Classroom added successfully.');
       // redirect user

       return redirect(route('classrooms.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Classroom $classroom)
    {
        return view('classrooms.create')->with('classroom', $classroom);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateClassroomRequest $request, Classroom $classroom)
    {
        $classroom->update([
            'ClassroomNo' => $request->ClassroomNo,
            'Desctiption' => $request->Desctiption,
            'Capacity' => $request->Capacity,
            'Laboratory' => $request->Laboratory,
            'Conversatory' => $request->Conversatory,
            'Lecture' => $request->Lecture,
            'Seminar' => $request->Seminar,   
       ]);
       // flash message
       session()->flash('success', 'Classroom updated successfully.');
       // redirect user

       return redirect(route('classrooms.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $classroom = Classroom::where('id', $id)->firstOrFail();
        $classroom->delete();
        session()->flash('success', 'Classroom deleted successfully.');

        return redirect(route('classrooms.index'));
    }

    /**
     * Export students to csv file
     *
     */

    public function export()
     {
        return Excel::download(new ClassroomsExport, 'classroom.csv');
     } 

     /**
     * Import csv file with students
     *
     */

     public function import() 
     {
         Excel::import(new ClassroomsImport,request()->file('file'));
            
         return back();
     }
}

resources/views/classrooms/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card card-default">
  <div class="card-header">
    {{ isset($classroom) ? 'Edit Classroom': 'Add Classroom' }}
  </div>

  <div class="card-body">
    @include('partials.errors')
    <form action="{{ isset($classroom) ? route('classrooms.update', $classroom->id) : route('classrooms.store') }}" method="POST">
      @csrf

      @if(isset($classroom))
        @method('PUT')
      @endif

      <div class="form-group">
        <label for="ClassroomNo">ClassroomNo</label>
        <input type="text" class="form-control" name="ClassroomNo" id='ClassroomNo' value="{{ isset($classroom) ? $classroom->ClassroomNo: '' }}">
      </div>
      <div class="form-group">
        <label for="Description">Description</label>
        <input type="text" class="form-control" name="Description" id='Description' value="{{ isset($classroom) ? $classroom->Description: '' }}">
      </div>
      <div class="form-group"> 
           {{-- Czy email ma jakas controlke? --}}
        <label for="Capacity">Capacity</label> 
        <input type="text" class="form-control" name="Capacity" id='Capacity' value="{{ isset($classroom) ? $classroom->Capacity: '' }}">
      </div>
      <div class="form-group">
           {{-- Tylko cyfry i max dlugosc --}}
        <label for="Laboratory">Laboratory</label>
        <input type="number" class="form-control" name="Laboratory" id='Laboratory' value="{{ isset($classroom) ? $classroom->Laboratory: '' }}">
      </div>
      <div class="form-group">
              {{-- wybieraczka jakas tam  --}}
          <label for="Conversatory">Conversatory</label>
          <input type="text" class="form-control" name="Conversatory" id='Conversatory' value="{{ isset($classroom) ? $classroom->Conversatory : '' }}">
     </div>
     <div class="form-group">
           {{-- tylko liczby i max dlugosc --}}
        <label for="Lecture">Lecture</label>
        <input type="number" class="form-control" name="Lecture" id='Lecture' value="{{ isset($classroom) ? $classroom->Lecture: '' }}">
      </div> 
      <div class="form-group">
        <label for="Seminar">Seminar</label>
        <input type="number" class="form-control" name="Seminar" id='Seminar' value="{{ isset($classroom) ? $classroom->Seminar: '' }}">
      </div>
    
      <div class="form-group">
        <a href="{{route('classrooms.index')}}" class="btn btn-secondary">Back</a>
        <button type="submit"  class="btn btn-secondary btn-lg">
          {{ isset($classroom) ? 'Update Classroom': 'Add Classroom' }}
        </button>        
      </div>
    </form>
  </div>
</div>
@endsection

@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

@endsection

@section('css')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
@endsection

resources/views/classrooms/index.blade.php
@extends('layouts.app')

@section('content')

  <div class="d-flex justify-content-end mb-2">
  <a href="{{ route('classrooms.create') }}" class="btn btn-secondary btn-lg">Add Classroom</a>
  </div>

  <div class="d-flex justify-content-end mb-5">
  <a href="{{ route('classrooms.export') }}" class="btn btn-secondary btn-lg">Export to csv</a>
  </div>
  <div class="d-flex justify-content-end mb-2">
  <form action="{{ route('classrooms.import') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <input type="file" name="file" class="form-control d-flex justify-content-end">
    <button class="btn btn-secondary btn-lg">Import Classroom</button>
  </div>

</div>


  <div class="card card-default">
    <div class="card-header">Classroom List</div>
  

  <div class="card-body">
     @include('partials.errors')
    @if($classrooms->count() > 0)
      <table class="table text-white">
        <thead>
          <th>ClassroomNo</th>
          <th>Description</th>
          <th>Capacity</th>
          <th>Laboratory</th>
          <th>Conversatory</th>
          <th>Lecture</th>
          <th>Seminar</th>
          <th></th>
          <th></th>
        </thead>
        <tbody>
          @foreach($classrooms as $classroom)
            <tr>
              <td>
                    {{-- name --}}
                    {{ $classroom->ClassroomNo }}
              </td>
              <td>
                {{-- Surname --}}
                {{ $classroom->Description }}
              </td>
               <td>
                {{-- Email --}}
                {{ $classroom->Capacity }}
              </td>
              <td>
               {{-- PhoneNumber --}}
               {{ $classroom->Laboratory }}
             </td>
             <td>
               {{-- DateOfBNirth --}}
               {{ $classroom->Conversatory }}
             </td>
             <td>
               {{-- Pesel --}}
               {{ $classroom->Lecture }}
             </td>
             <td>
              {{-- Pesel --}}
              {{ $classroom->Seminar }}
            </td>
             <td>
               <a href="{{ route('classrooms.edit', $classroom->id) }}" class="btn btn-secondary btn-sm">Edit</a>
             </td>
              <td>
              <form action="{{ route('classrooms.destroy', $classroom->id) }}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-secondary btn-sm">
                    Delete
                </button>
              </form>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
      {{$classrooms->links()}}
    @else
      <h3 class="text-center">No Classrooms Yet</h3>
    @endif
  
</div>

@endsection
@section('scripts')

@endsection

@section('css')

@endsection